channels:
  - conda-forge
dependencies:
  - python=3.12
  - flask=3.1.0       # builds REST API
  - gevent=24.11.1    # runs flask server
  - flask-socketio=5.5.1
  - pip
  - pip:
    - unsloth==2025.7.8